
/**
 * NOTE: This file should be placed in an `/api` directory for serverless function deployment
 * on platforms like Vercel or Netlify. The platform will automatically create the `/api/gemini` endpoint.
 */
import { GoogleGenAI, Type } from "@google/genai";
import { detectCrisis } from "../utils/crisisDetector"; 

export default async function handler(req: Request): Promise<Response> {
    if (req.method !== 'POST') {
        return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405, headers: { 'Content-Type': 'application/json' } });
    }

    try {
        const body = await req.json();

        if (body.action === 'generate_weekly_summary' || body.action === 'generate_monthly_summary') {
            const summary = await getSummary(body);
            return new Response(JSON.stringify(summary), { status: 200, headers: { 'Content-Type': 'application/json' } });
        } else {
            return new Response(JSON.stringify({ error: 'Invalid action' }), { status: 400, headers: { 'Content-Type': 'application/json' } });
        }
    } catch (error) {
        console.error('Error in API handler:', error);
        return new Response(JSON.stringify({ error: 'Internal server error' }), { status: 500, headers: { 'Content-Type': 'application/json' } });
    }
}


async function getSummary(data: any) {
    // --- CRISIS DETECTION ---
    const combinedText = data.entries.map((e: any) => e.rawText).join(' ');
    const severity = detectCrisis(combinedText);
    if (severity >= 2) {
        return { crisisDetected: true };
    }

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });
    const isMonthly = data.periodType === 'month';
    const periodLabel = isMonthly ? `Month ${data.period}` : `Week ${data.period}`;

    // --- GEMINI PROMPT TEMPLATE ---
    const systemInstruction = `You are an empathetic and insightful identity coach. Your task is to analyze a user's journal entries from the past ${data.periodType} and generate a structured, compassionate summary. The user is on a 90-day personal transformation journey. Your output must be a single, clean JSON object matching the provided schema.`;

    const userPrompt = `
        Please analyze the following data for ${data.userProfile.name}'s ${isMonthly ? 'monthly' : 'weekly'} summary.

        **User Context:**
        - Arc: ${data.userProfile.arc}
        - Ideal Self Manifesto: "${data.userProfile.idealSelfManifesto}"
        - Period: ${periodLabel}
        - Date Range: ${data.dateRange}

        **Journal Entries & Insights:**
        ${data.entries.map((e: any) => `[${e.type.toUpperCase()} on ${e.date}]: ${e.rawText}`).join('\n')}

        **Instructions:**
        Based on all the provided context and entries, generate a JSON object that synthesizes the user's growth and challenges.
    `;

    // --- SAFE SERVER-SIDE GEMINI CALL ---
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
        config: {
            systemInstruction,
            responseMimeType: 'application/json',
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    title: { type: Type.STRING, description: `A creative title for this ${data.periodType}'s summary` },
                    period: { type: Type.NUMBER },
                    dateRange: { type: Type.STRING },
                    stage: { type: Type.STRING, description: "A short descriptor of the current stage/arc" },
                    themes: { type: Type.ARRAY, items: { type: Type.STRING }, description: "3-5 bullet-point themes." },
                    challenges: { type: Type.ARRAY, items: { type: Type.STRING }, description: "2 bullet-point challenges or blocks." },
                    growth: {
                        type: Type.ARRAY,
                        items: {
                            type: Type.OBJECT,
                            properties: {
                                observation: { type: Type.STRING },
                                evidence: { type: Type.STRING, description: "A brief, direct quote from an entry that supports the observation." }
                            }
                        },
                        description: "3-4 concise observations of growth."
                    },
                    notableExcerpts: { type: Type.ARRAY, items: { type: Type.STRING }, description: "2-3 impactful user-written quotes." },
                    actionPlan: { type: Type.ARRAY, items: { type: Type.STRING }, description: "3 bite-sized steps for the next period." },
                    encouragement: { type: Type.STRING, description: "A short, warm, empowering closing paragraph." }
                },
            }
        }
    });

    const summaryJson = JSON.parse(response.text);
    
    // Add metrics that were passed in, not generated by the AI
    summaryJson.metrics = {
        entries: data.entries.length,
        streak: data.streak,
        completionRate: `${Math.round(data.checkinCompletionRate * 100)}%`
    };

    return summaryJson;
}
